### ISSUE TITLE
Result folder

### ISSUE THREAD

**Issue by Sondr11** [seqinfo/BinDel#1]
I have read and tested Bindel.  I want to ask about where the folder containing the link is located?  What is the minimum reference sample size?
Thank you

**Comment by Sondr11** [comment]
Hi
I used Bindel for microdeletion 22q11.2. I created reference and determined correct microdeletion. I used code: R::infer_normality("sample.bam", "reference.gz").
But I see that the output data is just 1 table with risk scores.  I looked at the code and found that Bindel allows creating charts with create_bin_plot.  I ran Bindel according to the function below:
R::infer_normality("sample.bam", "reference.gz", creat_bin_plot = TRUE, save_bin = TRUE)
but I got an error.
Am I running the above code correctly?
Thank you so much

**Comment by PriitPaluoja** [comment]
Thank you for your question. We greatly appreciate your feedback. In response to your inquiry, we are updating the README to ensure clarity in usage.

Results location: The output file name and location are determined by the function `infer_normality` named parameter `output_file_path` (presumes that the folder exists) and `score_file_extension`. Based on our analysis, we recommend using the column `conservative_prob` from the resulting output file for standard WGS NIPT to estimate microdeletion risk. 

The `conservative_prob` is a probability of microdeletion risk with a risk score between 0-100, where 100 represents the highest risk. In non-standard NIPT analysis (exploratory or novel method development), one might benefit from using `dist_conservative` Mahalanobis distance (set `output_intermediate_scores = T`), which is not capped at 100 but requires distribution analysis to determine where to set high microdeletion cut-off. Please note that the risk score interpretation may vary between different NIPT WGS protocols.

Minimum reference sample size: for regular WGS NIPT, we recommend at least 200 samples for the analysis. The reference sample set size is not constrained, but PCA-based normalisation yields more accurate analysis when an increased number of euploid fetus samples are used as a reference. Furthermore, small reference set size and high cumulative PCA settings (regional, `use_pca_per_region = T` and `cumulative_variance_per_region = 50`) may lead to NA microdeletion risk scores or the inability to call microdeletion risk accurately.

We have documented the `infer_normality` function within BinDel, providing details on configuring analysis and output-related parameters according to specific needs. If you have further questions or require assistance, please feel free to reach out.

Regarding the bin plot error, could you please specify the error message? Also, were you running BinDel in a docker container, and if not, which operating system?

**Comment by Sondr11** [comment]
Hì
Thank you for your response.  Regarding the chart error, I have already fixed it, the cause is missing "ragg" package.  I have a question about the value of the column "conservative_prob", the cut-off threshold to determine whether or not the microdeletion?
Thank you so much.

**Comment by PriitPaluoja** [comment]
Based on the [preprint](https://www.medrxiv.org/content/10.1101/2022.09.20.22280152v2.full-text), the recommended approach would be adopting a microdeletion-region-specific cut-off threshold when NIPT samples featuring microdeletions are available for calibration. This calibration should encompass parameters such as `cumulative_variance`, `use_pca_per_region` ,`cumulative_variance_per_region`, and the cut-off threshold, tailored to align with the application’s specific requirements, ensuring a balance between sensitivity and specificity that aligns with the intended analysis purposes.
