### ISSUE TITLE
Add reference 

### ISSUE THREAD

**Issue by Sondr11** [seqinfo/BinDel#2]
Hì.
I tried to run the reference with 200 samples but my RAM memory is not enough.  Can I create a reference with 50 samples then add some samples to the previous reference?
Thank you

**Comment by PriitPaluoja** [comment]
Hi!

Yes, it is possible, as the reference file is tab separate text file. You can, for example, create a reference with the first 50 samples as usual:
`write_reference(c("sample1.bam", ... "sample50.bam")), "coordinates.tsv", "reference_with_header.gz")`

But for the next 50 samples without the column names/header:
`write_reference(c("sample51.bam", ... "sample100.bam")), "coordinates.tsv", "reference_no_header.gz", col_names = FALSE)`

And then finally merge `reference_with_header` and `reference_no_header.gz`
`cat reference_with_header reference_no_header.gz > reference.gz`

**Comment by Sondr11** [comment]
Hì.
That's so great.
Thank you so much

**Comment by Sondr11** [comment]
Hi. 
I followed your instructions on dividing the reference into 2 parts: ref1.gz with header (70 sample) and ref2.gz without header (50 sample) then I merged with the command:
cat ref1.gz ref2.gz > ref.gz

When I tested on the sample to call microdeletion with ref.gz, it gave an error.  same sample, I call microdeletion with ref1.gz and it doesn't error

I observed that my ref.gz should have 120 samples.  but I realized that it only has 50 samples exactly the same as the sample number of ref2.gz.
I opened ref.gz and saw that the sample numbers were numbered intermittently.  it starts from 1 to 70 then again from 1 to 50.

**Comment by PriitPaluoja** [comment]
Indeed, the sample name overlapping issue arises, my apologies for any inconvenience caused. Please address it by including the `anonymise=F` when creating a reference: `write_reference(..., anonymise=F)`.

**Comment by Sondr11** [comment]
anonymise=F. I used it for ref1,gz and ref2.gz. After I run command: cat ref1.gz ref2.gz > ref.gz
I understand that, right?
Thank you so much

**Comment by PriitPaluoja** [comment]
Yes, `cat ref1.gz ref2.gz > ref.gz `should work.
